- repo: local
  hooks:
  - id: validate-generated-templates
    name: Validate generated templates
    entry: ./install/support/validate-generated-templates.sh
    language: script
    files: ^install/generator/.+\.mustache$
