apiVersion: v1
kind: ServiceAccount
metadata:
  name: ipaas-oauth-client
  labels:
    app: redhat-ipaas
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.local: http://localhost:4200
    serviceaccounts.openshift.io/oauth-redirectreference.route: '{"kind": "OAuthRedirectReference", "apiVersion": "v1", "reference": {"kind": "Route","name": "ipaas-ui"}}'
