---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    funktion.fabric8.io/kind: Connector
  name: k8elasticsearch
data:
  deployment.yml: |
    ---
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        funktion.fabric8.io/kind: Subscription
        connector: k8elasticsearch
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            funktion.fabric8.io/kind: Subscription
            connector: k8elasticsearch
        spec:
          containers:
          - image: funktion/connector-k8elasticsearch:${project.version}
            name: connector
  schema.yml: |
    ---
    component:
      kind: component
      scheme: k8elasticsearch
      syntax: k8elasticsearch:Operation
      title: ElasticSearch
      description: Funktion - ElasticSearch component finessed to work well with Kubernetes
      label: monitoring,search
      deprecated: false
      async: false
      producerOnly: true
      javaType: io.fabric8.funktion.camel.components.k8elasticsearch.K8ElasticSearchComponent
      groupId: io.fabric8.funktion.camel-k8
      artifactId: k8elasticsearch
      version: 1.0-SNAPSHOT
    componentProperties:
      client:
        kind: property
        type: object
        javaType: org.elasticsearch.client.Client
        deprecated: false
        secret: false
        order: 0
    properties:
      clusterName:
        kind: path
        group: producer
        required: true
        type: string
        javaType: java.lang.String
        deprecated: false
        secret: false
        order: 0
      clientTransportSniff:
        kind: parameter
        group: producer
        type: boolean
        javaType: java.lang.Boolean
        deprecated: false
        secret: false
        defaultValue: true
        order: 1
      consistencyLevel:
        kind: parameter
        group: producer
        type: string
        javaType: org.elasticsearch.action.WriteConsistencyLevel
        enum:
        - DEFAULT
        - ONE
        - QUORUM
        - ALL
        deprecated: false
        secret: false
        defaultValue: DEFAULT
        order: 2
      data:
        kind: parameter
        group: producer
        type: boolean
        javaType: java.lang.Boolean
        deprecated: false
        secret: false
        order: 3
      indexName:
        kind: parameter
        group: producer
        type: string
        javaType: java.lang.String
        deprecated: false
        secret: false
        order: 4
      indexType:
        kind: parameter
        group: producer
        type: string
        javaType: java.lang.String
        deprecated: false
        secret: false
        order: 5
      ip:
        kind: parameter
        group: producer
        type: string
        javaType: java.lang.String
        deprecated: false
        secret: false
        order: 6
      operation:
        kind: parameter
        group: producer
        type: string
        javaType: java.lang.String
        enum:
        - INDEX
        - UPDATE
        - BULK
        - BULK_INDEX
        - GET_BY_ID
        - MULTIGET
        - DELETE
        - EXISTS
        - SEARCH
        - MULTISEARCH
        deprecated: false
        secret: false
        order: 7
      pathHome:
        kind: parameter
        group: producer
        type: string
        javaType: java.lang.String
        deprecated: false
        secret: false
        defaultValue: ${user.home}/.elasticsearch
        order: 8
      port:
        kind: parameter
        group: producer
        type: integer
        javaType: int
        deprecated: false
        secret: false
        defaultValue: "9300"
        order: 9
      transportAddresses:
        kind: parameter
        group: producer
        type: string
        javaType: java.lang.String
        deprecated: false
        secret: false
        order: 10
      synchronous:
        kind: parameter
        group: advanced
        label: advanced
        type: boolean
        javaType: boolean
        deprecated: false
        secret: false
        defaultValue: false
        description: Sets whether synchronous processing should be strictly used or Camel is allowed to use asynchronous processing (if supported).
        order: 11
      serviceName:
        kind: parameter
        group: serviceName
        label: serviceName
        type: string
        javaType: java.lang.String
        deprecated: false
        secret: false
        defaultValue: elasticsearch
        order: 12
