#
# Copyright (C) 2016 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: 2
jobs:
  build:
    working_directory: /workspace
    docker:
    - image: openjdk:8-jdk
    environment:
      MAVEN_OPTS: -Xmx1024m
      DOCKER_VERSION: 17.04.0-ce

    steps:
      - setup_remote_docker

      - checkout

      # - s2iore_cache:
      #     key: syndesis-s2i-image-m2

      # - run:
      #     name: Maven
      #     command: ./mvnw --batch-mode -U -Pfabric8 install

      # - save_cache:
      #     key: syndesis-s2i-m2
      #     paths:
      #     - ~/.m2

      - deploy:
          command: |
            if [ "${CIRCLE_PROJECT_USERNAME}" != "syndesisio" ]; then
              exit 0
            fi

            curl -fsSL https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz | tar xz -C /usr/bin --strip-components 1

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              ./run.sh --to syndesis/syndesis-s2i:latest
              docker push syndesis/syndesis-s2i:latest | cat -
            fi
            
            # if [[ "${CIRCLE_TAG}" =~ ^[0-9]+(\.[0-9]+){2} ]]; then
            #   docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            #   ./run.sh --to syndesis/syndesis-s2i:${CIRCLE_TAG}
            #   docker push syndesis/syndesis-s2i:${CIRCLE_TAG} | cat -
            #   docker tag syndesis/syndesis-s2i:${CIRCLE_TAG} syndesis/syndesis-s2i:$(echo ${CIRCLE_TAG} | sed -e 's/\.[0-9][0-9]*$//')
            #   docker push syndesis/syndesis-s2i:$(echo ${CIRCLE_TAG} | sed -e 's/\.[0-9][0-9]*$//')
            # fi
