apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: syndeses.syndesis.io
spec:
  group: syndesis.io
  names:
    kind: Syndesis
    listKind: SyndesisList
    plural: syndeses
    singular: syndesis
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
