apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/component: syndesis-server
    syndesis.io/type: infrastructure
    monitoring-key: middleware
    application-monitoring: "true"
  name: syndesis-server
spec:
  endpoints:
  - port: prometheus
  selector:
    matchLabels:
      syndesis.io/component: syndesis-server