apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: infrastructure
    prometheus: application-monitoring
    role: alert-rules
    monitoring-key: middleware
    application-monitoring: "true"
  name: syndesis-jvm-rules
spec:
  groups:
    - name: syndesis-jvm.rules
      rules:
        # Alert for any syndesis-meta or syndesis-server instance that has used 90% of heap memory
        - alert: FuseOnlineInfrastructureJvmHeapThresholdExceeded
          annotations:
            message: >-
              Fuse Online service {{$labels.service}} in pod {{$labels.pod}}, namespace {{$labels.namespace}}, has used {{printf "%0.0f" $value}}% of {{$labels.area}} memory.
          expr: >
            sum(jvm_memory_used_bytes{area="heap", job=~"syndesis-meta|syndesis-server"}) / sum(jvm_memory_max_bytes{area="heap", job=~"syndesis-meta|syndesis-server" }) * 100 >= 90
          for: 5m
          labels:
            severity: warning

        # Alert for any syndesis-meta or syndesis-server instance that has used 90% of nonheap memory
        - alert: FuseOnlineInfrastructureJvmNonHeapThresholdExceeded
          annotations:
            message: >-
              Fuse Online service {{$labels.service}} in pod {{$labels.pod}}, namespace {{$labels.namespace}}, has used {{printf "%0.0f" $value}}% of {{$labels.area}} memory.
          expr: |
            sum(jvm_memory_used_bytes{area="nonheap", job=~"syndesis-meta|syndesis-server"}) / sum(jvm_memory_max_bytes{area="nonheap", job=~"syndesis-meta|syndesis-server" }) * 100 >= 90
          for: 5m
          labels:
            severity: warning

        # Alert for any syndesis-meta or syndesis-server instance that has deadlocked threads
        - alert: FuseOnlineInfrastructureJvmDeadlockedThreads
          annotations:
            message: >-
              Fuse Online service {{$labels.service}} in pod {{$labels.pod}}, namespace {{$labels.namespace}}, has {{$value}} blocked threads.
          expr: |
            jvm_threads_states_threads{state="blocked", job=~"syndesis-meta|syndesis-server"} > 0
          for: 5m
          labels:
            severity: warning


